### ISSUE TITLE
EULA not accepted

### ISSUE THREAD

**Issue by queglay** [dbhagen/sidefx-hkey-docker#1]
Nice work on this, I'm looking forward to trying it out!  I had a shot but had issues with the access token and accepting the eula-

Traceback (most recent call last):
  File "/root/downloadHoudini.py", line 164, in <module>
    latest_release = service.download.get_daily_build_download(
  File "/root/downloadHoudini.py", line 51, in __call__
    return call_api_with_access_token(
  File "/root/downloadHoudini.py", line 112, in call_api_with_access_token
    raise APIError(
__main__.APIError: EULA not accepted. Please visit https://www.sidefx.com/services/eula/

**Comment by queglay** [comment]
This was the thing I was missing, it wasn't clear to me how to generate the Id and Secret:
https://www.sidefx.com/docs/api/credentials/index.html
